name: "Plan (post)"

on:
  workflow_run:
    workflows:
      - Plan
    types:
      - completed

jobs:
  notify:
    permissions:
      statuses: write
    name: "Notify"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sha="$(gh run view --verbose '${{ github.event.workflow_run.id }}' --repo '${{ github.repository }}' | grep -Pom1 "repos/${{ github.repository }}/statuses/\K[a-z0-9]+"
          gh api "repos/${{ github.repository }}/statuses/$sha" -f context='Plan' -f state='${{ github.event.workflow_run.conclusion }}' -f target_url='${{ github.event.workflow_run.html_url }}'
